# Use case configuration for OPPO Pad 5 Pro/OnePlus Pad 3 Pro/OnePlus Pad 4
# Author: map220v <map220v300@gmail.com>

Syntax 4

SectionUseCase."HiFi" {
	File "/OnePlus/iceland/HiFi.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='RX_RX0 Digital Volume' 84"
	cset "name='RX_RX1 Digital Volume' 84"
	cset "name='RX_COMP1 Switch' 0"
	cset "name='RX_COMP2 Switch' 0"
	cset "name='HPHL Volume' 20"
	cset "name='HPHR Volume' 20"
]

# WCD939X specific volume control settings
LibraryConfig.remap.Config {
	ctl.default.map {
		# Merge two mono controls into one stereo
		"name='HP Volume'" {
			"name='HPHL Volume'".vindex.0 0
			"name='HPHR Volume'".vindex.1 0
		}
		"name='ADC31 Volume'" {
			"name='ADC3 Volume'".vindex.0 0
			"name='ADC1 Volume'".vindex.1 0
		}
	}
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
